name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.4"
      - name: Deps
        run: |
          make dev-deps
      - name: Vet
        run: |
          make vet
      - name: Tests
        run: |
          make test-coverage
