name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.4"
      - name: Vet
        run: |
          make vet
      - name: Tests
        run: |
          make test-coverage
